### ISSUE TITLE
Build breaks due to missing rustorm/dao/Cargo.toml

### ISSUE THREAD

**Issue by Ran4** [ivanceras/diwata#4]
Following the "Install dependencies" step in README.md, during the "Compile and run" steps,

running e.g. `cargo run -p diwata -- --help` gives me the error 

```
error: failed to read `/tmp/diwata/rustorm/dao/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```

See https://github.com/rust-lang/rust/issues/40284 and https://github.com/rust-lang/rust/pull/40297

A simple solution (that at least make the program run) is to add `git submodule update --init` as a step before the `cargo run...` line, but I'm not sure if that's really what you want.

---

I'm using

* Ubuntu 17.10
* Git version 2.15.1
* rustc 1.26.0-nightly (2789b067d 2018-03-06)

**Comment by ivanceras** [comment]
@Ran4 Thank your for your interest on this project. 
I've updated the README file and fix dependencies to use the ones that is published on crates.io. Do a git pull and try build again, it should build now.

**Comment by Ran4** [comment]
Thanks. The new instructions removed the `rustup override set nightly` command though (which is helpful, especially for non-rust-users, I suppose?), so it still doesn't build according to the instructions:

```
$ cargo run -p diwata -- --help
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading serde v1.0.29
 Downloading serde_derive v1.0.29
 Downloading rustorm v0.10.1
 Downloading rustorm_codegen v0.1.1
 Downloading serde_json v1.0.11
 Downloading rustorm_dao v0.1.0
 Downloading quote v0.4.2
 Downloading syn v0.12.14
 Downloading proc-macro2 v0.2.3
 Downloading serde_derive_internals v0.20.0
 Downloading unicode-xid v0.1.0
 Downloading cc v1.0.6
 Downloading atty v0.2.8
   Compiling pear v0.0.12
   Compiling byteorder v1.2.1
   Compiling yansi v0.3.4
   Compiling typeable v0.1.2
error[E0554]: #![feature] may not be used on the stable release channel
 --> /home/ran/.cargo/registry/src/github.com-1ecc6299db9ec823/yansi-0.3.4/src/lib.rs:1:32
  |
1 | #![cfg_attr(feature="nightly", feature(const_atomic_bool_new))]
  |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `yansi`.
warning: build failed, waiting for other jobs to finish...
error: build failed

```

(everything works fine if you would re-add the `rustup override set nightly` command).

Do note that this is mostly nitpicking from me of course, a rust programmer would probably figure this out on their own with no issues, but I'm not sure who you are targeting at the moment. Being able to set something up by following the readme is usually quite valuable :)

**Comment by ivanceras** [comment]
@Ran4 , you are right I mistakenly remove the nightly override. That's what happen when trying to fix 2 repo at the same time ( was trying to make the other repo compile to stable). Thanks for letting me know.

**Comment by ivanceras** [comment]
This has been fixed in recent builds
